filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: ""  # Leave empty if security disabled

setup.kibana:
  host: "http://kibana:5601"

processors:
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

logging.level: info
